apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
  namespace: sn-labs-bonillamigue
spec:
  workspaces:
    - name: output
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: output
    - name: flake8-linting
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output
    - name: nose-tests
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output
    - name: buildah-task
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: output
    - name: oc-deploy
      taskRef:
        name: oc-deploy
      params:
        - name: app-name
          value: your-app-name  # Replace with your application name
        - name: build-image
          value: your-build-image  # Replace with your build image
      workspaces:
        - name: output
          workspace: output
